"use client";
import '@/app/atlas.css';
import '@/app/workflow.css';
import '@/app/network-refinement.css';
import '@/app/workflow-ribbon.css';
import '@/app/compact-funnels.css';
import '@/app/network-studio.css';
import '@/app/reader-polish.css';
import '@/app/homology-presentation.css';
import {lazy,Suspense,useEffect,useMemo,useState} from 'react';
import {Dna,LayoutDashboard,Database,CircleDot,Waypoints,Layers3,Network,GitMerge,Users,BookOpen,Search,Download,ChevronRight,Lock,FileText,Focus} from 'lucide-react';
import {ColumnDef} from '@tanstack/react-table';
import {Sidebar,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarHeader,SidebarInset,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import ResearchOverview from '@/components/research-overview';
import WorkflowMap from '@/components/workflow-map';
import {workspaceNames} from '@/lib/workflow';
import DataTable from '@/components/data-table';
import StageAtlas from '@/components/stage-atlases';
import InteractionAtlas from '@/components/interaction-atlas';
import ExtensionAtlas from '@/components/extension-atlas';
import ProteinDetail from '@/components/protein-detail';
import {ReaderBody} from '@/components/atlas-methods';
import {Release,Candidate,Route,Doc,sections,fmt,routeLabels,exportTSV} from '@/lib/release';
import {useReadonlyTools} from '@/lib/use-readonly-tools';
const NucleusModelWorkspace=lazy(()=>import('@/components/nucleus-model-workspace'));

const navBase=[['overview','研究概览',LayoutDashboard],['reference','蛋白参考库',Database],['a','核定位图谱',CircleDot],['b2','调控网络图谱',Waypoints],['b3','可变异构体图谱',Layers3],['pairs','蛋白互作图谱',Network],['stage25','同源功能扩展',GitMerge],['candidates','候选蛋白库',Users],['downloads','方法与数据来源',BookOpen]] as const;
const nav=navBase.map(([id,,Icon])=>[id,workspaceNames[id],Icon] as const);
const legacy:Record<string,string>={stage0:'reference',stage2:'pairs',version:'downloads',nuclear:'a'};
function Navigation({page,go}:{page:string;go:(p:string)=>void}){const {setOpenMobile}=useSidebar();return <Sidebar className="research-sidebar"><SidebarHeader><button className="brand" onClick={()=>go('overview')}><span className="brand-mark"><Dna size={26}/></span><span>表观调控图谱<small>候选发现与证据分析</small></span></button></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>研究工作区</SidebarGroupLabel><SidebarMenu>{nav.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton className="nav-item" isActive={page===id||id==='a'&&page==='b1'} onClick={()=>{go(id);setOpenMobile(false)}}><Icon size={18}/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><SidebarGroup><SidebarGroupLabel>模型研究</SidebarGroupLabel><SidebarMenu><SidebarMenuItem><SidebarMenuButton className="nav-item" isActive={page==='nucleus-model'} onClick={()=>{go('nucleus-model');setOpenMobile(false)}}><Focus size={18}/><span>{workspaceNames['nucleus-model']}</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><div className="sidebar-note"><Dna size={22}/><strong>蛋白与调控证据</strong><span>核定位 · 功能网络 · 蛋白互作</span></div><div className="local-status"><i/>公开研究工作台<Lock size={13}/></div></SidebarFooter></Sidebar>}
export default function AtlasWorkspace(){const [release,setRelease]=useState<Release|null>(null),[docs,setDocs]=useState<Doc[]>([]),[error,setError]=useState(''),[page,setPage]=useState('overview'),[query,setQuery]=useState(''),[route,setRoute]=useState('all'),[protein,setProtein]=useState('');useReadonlyTools(release);
 useEffect(()=>{Promise.all([fetch('/Protein_digger/data/release.json').then(r=>{if(!r.ok)throw Error('交付数据包未能载入');return r.json()}),fetch('/Protein_digger/atlas/documents.json').then(r=>{if(!r.ok)throw Error('研究方法目录未能载入');return r.json()})]).then(([d,m])=>{setRelease(d as Release);setDocs(m as Doc[])}).catch(e=>setError(e.message));const read=()=>{const p=new URLSearchParams(location.hash.slice(1));const raw=p.get('view')||'overview';setPage(legacy[raw]||raw);setQuery(p.get('q')||'');setRoute(p.get('route')||'all');setProtein(p.get('protein')||'')};read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read)},[]);
 const go=(p:string,q='',r='all')=>{const id=legacy[p]||p;const params=new URLSearchParams({view:id});if(q)params.set('q',q);if(r!=='all')params.set('route',r);location.hash=params.toString();setPage(id);setQuery(q);setRoute(r);setProtein('');window.scrollTo({top:0})};
 const sync=(key:string,value:string)=>{const p=new URLSearchParams(location.hash.slice(1));if(value&&value!=='all')p.set(key,value);else p.delete(key);history.replaceState(null,'','#'+p.toString())};
 const changeQuery=(q:string)=>{setQuery(q);sync('q',q)};const changeRoute=(r:string)=>{setRoute(r);sync('route',r)};const selectProtein=(id:string)=>{setProtein(id);sync('protein',id)};
 const candidates=useMemo(()=>release?.candidates.filter(r=>(route==='all'||r.route===route)&&`${r.gene} ${r.name} ${r.accessions.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase()))||[],[release,route,query]);
 const cols:ColumnDef<Candidate>[]=[{accessorKey:'gene',header:'候选基因',cell:({row})=><button className="gene-link" onClick={()=>selectProtein(row.original.accessions[0])}>{row.original.gene}</button>},{accessorKey:'route',header:'筛选路径',cell:({row})=><span className={`route-tag route-${row.original.route}`}>{row.original.route}</span>},{id:'accessions',accessorFn:r=>r.accessions.join('; '),header:'蛋白编号',cell:({row})=><div className="accession-chips">{row.original.accessions.map(id=><button onClick={()=>selectProtein(id)} key={id}>{id}</button>)}</div>},{accessorKey:'name',header:'蛋白名称',cell:({getValue})=><span className="protein-name">{String(getValue())}</span>},{accessorKey:'row',header:'来源行号'}];
 const title=workspaceNames[page]||'研究工作区';const section=sections.find(s=>s.id===page);const description=page==='reference'?'人类审校代表序列、核定位注释与调控锚点。':page==='a'?'核定位注释及调控功能证据分层。':page==='b1'?'完整序列评分、固定筛选条件与定位证据。' :page==='b2'?'基于功能注释与有向调控网络评价候选蛋白的调控邻近性。':page==='b3'?'可变异构体的序列、定位与联合互作证据。':page==='stage25'?'基于同源与功能支持的独立扩展，不作为直接互作证据。':page==='pairs'?'候选蛋白与调控锚点之间的实验记录和模型预测。':page==='candidates'?'四条筛选路径的最终候选，保留基因、蛋白及异构体之间的对应关系。':section?.summary||'';
 const search=<div className="search-input"><Search size={18}/><Input aria-label="搜索候选蛋白" placeholder="基因、UniProt编号或蛋白名称" value={query} onChange={e=>changeQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&page==='overview')go('candidates',query)}}/></div>;
 return <SidebarProvider style={{'--sidebar-width':'264px'} as React.CSSProperties}><Navigation page={page} go={go}/><SidebarInset className="workspace-main"><header className="topbar"><div><SidebarTrigger/><span>研究工作区</span><ChevronRight size={14}/><strong>{title}</strong></div><span className="top-status">研究数据 · 只读</span></header><main className="workspace-content">{!release?<div className="panel loading">{error||'正在载入研究数据…'}</div>:<>
 {page!=='overview'&&<div className="page-heading"><div><h1>{title}</h1>{description&&<p>{description}</p>}</div></div>}
 {page==='overview'&&<ResearchOverview release={release} search={search} query={query} go={go}><DataTable data={candidates.slice(0,8)} columns={cols} label="候选蛋白浏览"/></ResearchOverview>}
 {page!=='overview'&&page!=='downloads'&&page!=='nucleus-model'&&<WorkflowMap page={page} go={go}/>}
 {page==='nucleus-model'&&<Suspense fallback={<div className="panel loading">正在载入模型工作区…</div>}><NucleusModelWorkspace onB1={()=>go('b1')}/></Suspense>}
 {['reference','a','b1','b2','b3'].includes(page)&&<StageAtlas page={page} query={query} onQuery={changeQuery} onProtein={selectProtein} go={go} docs={docs}/>}
 {page==='pairs'&&<InteractionAtlas release={release} query={query} onQuery={changeQuery} onProtein={selectProtein} docs={docs} route={route} onRoute={changeRoute}/>}
 {page==='stage25'&&<ExtensionAtlas query={query} onQuery={changeQuery} onProtein={selectProtein} docs={docs}/>}
 {page==='candidates'&&<><div className="atlas-stats">{(['A','B1','B2','B3'] as Route[]).map(r=><button key={r} className={route===r?'selected':''} onClick={()=>changeRoute(route===r?'all':r)}><span>{r} · {routeLabels[r]}</span><strong>{fmt(release.counts.route_rows[r])}</strong><small>{r==='B3'?'基因记录 · 152条异构体':'候选记录'}</small></button>)}</div><div className="filterbar">{search}<Select value={route} onValueChange={changeRoute}><SelectTrigger className="filter-select" aria-label="筛选候选路径"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部筛选路径</SelectItem>{(['A','B1','B2','B3'] as Route[]).map(r=><SelectItem key={r} value={r}>{r}</SelectItem>)}</SelectContent></Select><Button variant="outline" disabled={!candidates.length} onClick={()=>exportTSV('候选蛋白_当前筛选.tsv',candidates.map(r=>({...r,accessions:r.accessions.join(';')})))}><Download size={15}/>导出{fmt(candidates.length)}条</Button></div><DataTable data={candidates} columns={cols} label="最终候选蛋白库"/><div className="notice">主表保留1,580条筛选路径记录，对应1,573个唯一基因、1,620个蛋白编号。同源功能扩展9条单独展示，不混入本表。<button className="text-link" onClick={()=>go('stage25')}>查看扩展附表</button></div></>}
 {page==='downloads'&&<MethodsAndSources docs={docs} release={release}/>}
 </>}<footer className="content-footer"><span>表观调控候选发现与证据分析</span><span>公开只读 · 无在线预测</span></footer></main></SidebarInset>{release&&<ProteinDetail accession={protein} onSelect={selectProtein} onClose={()=>selectProtein('')} release={release} onPairs={id=>go('pairs',id)}/>}</SidebarProvider>
}
function MethodsAndSources({docs,release}:{docs:Doc[];release:Release}){const [open,setOpen]=useState('');return <><section className="download-banner"><FileText size={30}/><div><strong>第一批候选基因与对应蛋白</strong><p>原始候选与互作配对表</p></div><Button asChild><a href="/Protein_digger/downloads/第一批候选基因与对应蛋白.xlsx" download>下载Excel</a></Button></section><section className="panel method-downloads">{docs.map(d=><div key={d.id}><BookOpen size={18}/><div><strong>{d.title}</strong></div><button className="text-link" onClick={()=>setOpen(open===d.id?'':d.id)}>预览</button><a href={`/Protein_digger/reader-methods/${encodeURIComponent(d.file)}`} download>MD</a><a href={`/Protein_digger/reader-methods/${encodeURIComponent(d.file.replace(/\.md$/,'.pdf'))}`} download>PDF</a></div>)}</section>{open&&docs.find(d=>d.id===open)&&<section className="panel document-panel"><ReaderBody doc={docs.find(d=>d.id===open)!}/></section>}<section className="panel result-summary"><h2>数据版本与解释范围</h2><dl><dt>结果集合</dt><dd>当前候选与互作配对集合</dd><dt>方法与网络展示</dt><dd>使用冻结数据，未重新预测或改变候选</dd><dt>B3分支</dt><dd>保守分支，使用历史B1的1,340条排除集合</dd><dt>同源功能扩展</dt><dd>当前 A1_WIDE、修正 B1 与重建 B2；独立9条扩展附表</dd></dl><div className="resource-links"><a href="/Protein_digger/atlas/source_manifest.json" download>阶段数据版本与校验清单</a><a href="/Protein_digger/atlas/manifest.json" download>图谱索引清单</a><a href="/Protein_digger/atlas/extension_provenance.json" download>同源扩展来源校验</a><a href="/Protein_digger/reader-methods/研究方法汇编.pdf" download>完整方法PDF汇编</a></div><details><summary>数据校验与指标字典</summary><p className="checksum">Excel SHA256：<code>{release.counts.excel_sha256}</code></p><p>原始交付表与冻结结果保持不变。公共清单记录发布文件校验值；科研服务器路径与运行日志不包含在站点内。</p><div className="resource-links"><a href="/Protein_digger/publication-manifest.json" download>公开文件校验清单</a><a href="/Protein_digger/methods/process_dictionary.tsv" download>功能过程字典</a><a href="/Protein_digger/methods/metric_dictionary.tsv" download>指标字典</a></div></details></section></>}
