"use client";
import {useEffect,useMemo,useState} from 'react';
import {ColumnDef} from '@tanstack/react-table';
import {Download,Search,RotateCcw,Info,ArrowLeft,Orbit,Focus,ChevronLeft,ChevronRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import DataTable from '@/components/data-table';
import {pairGraph,endpoint} from '@/components/atlas-graph';
import {PairOverview,RadialRelations,roleName} from '@/components/interaction-explorer-graph';
import AtlasMethods from '@/components/atlas-methods';
import ReaderNote from '@/components/reader-note';
import ReleaseFunnel from '@/components/release-funnel';
import {Release,Pair,Doc,Route,fmt,pairKey,routeLabels,exportTSV} from '@/lib/release';
import {display} from '@/lib/atlas';
export default function InteractionAtlas({release,query,onQuery,onProtein,docs,route,onRoute}:{release:Release;query:string;onQuery:(s:string)=>void;onProtein:(s:string)=>void;docs:Doc[];route:string;onRoute:(s:string)=>void}){
 const [evidence,setEvidence]=useState('all'),[unique,setUnique]=useState(false),[focus,setFocus]=useState(''),[selected,setSelected]=useState(''),[history,setHistory]=useState<string[]>([]),[all,setAll]=useState(false);
 const [edge,setEdge]=useState<Pair[]|null>(null),[plm,setPlm]=useState(''),[pplm,setPplm]=useState(''),[find,setFind]=useState(''),[partnerQuery,setPartnerQuery]=useState(''),[partnerPage,setPartnerPage]=useState(0),[limit,setLimit]=useState(40);
 const filtered=useMemo(()=>release.pairs.filter(p=>(route==='all'||p.route===route)&&(p.gene+' '+p.candidate+' '+p.anchorGene+' '+p.anchor).toLowerCase().includes(query.toLowerCase().trim())&&(evidence==='all'||evidence==='hi'&&p.evidence.includes('HI-union')||evidence==='rf'&&p.evidence.includes('RF2')||evidence==='iso'&&p.route==='B3')&&(!plm||p.plm!==null&&p.plm>=Number(plm))&&(!pplm||p.pplm!==null&&p.pplm>=Number(pplm))),[release,query,route,evidence,plm,pplm]);
 const graph=useMemo(()=>pairGraph(filtered),[filtered]),nodes=useMemo(()=>new Map(graph.nodes.map(n=>[n.id,n])),[graph]);
 const defaultFocus=useMemo(()=>[...graph.nodes].filter(n=>n.kind!=='anchor').sort((a,b)=>(b.degree||0)-(a.degree||0)||a.id.localeCompare(b.id))[0]?.id||'',[graph]);
 useEffect(()=>{if(!nodes.has(focus)){setFocus(defaultFocus);setSelected(defaultFocus);setHistory([])}else if(selected&&!nodes.has(selected))setSelected(focus)},[nodes,focus,defaultFocus,selected]);
 useEffect(()=>{setLimit(40);setPartnerQuery('');setPartnerPage(0)},[focus]);
 useEffect(()=>setPartnerPage(0),[partnerQuery,filtered]);
 const choose=(id:string)=>{if(!nodes.has(id))return;if(focus&&id!==focus)setHistory(h=>[...h,focus]);setFocus(id);setSelected(id);setAll(false);setFind('')};
 const activate=(id:string)=>{if(!nodes.has(id))return;choose(id);setEdge(null);onProtein(id)};
 const previous=()=>{const valid=history.filter(id=>nodes.has(id));if(!valid.length)return;const id=valid.pop()!;setHistory(valid);setFocus(id);setSelected(id);setAll(false)};
 const localEdges=useMemo(()=>graph.links.filter(e=>endpoint(e.source)===focus||endpoint(e.target)===focus),[graph,focus]);
 const partners=useMemo(()=>localEdges.map(e=>({node:nodes.get(endpoint(e.source)===focus?endpoint(e.target):endpoint(e.source))!,edge:e})).sort((a,b)=>a.node.label.localeCompare(b.node.label)||a.node.id.localeCompare(b.node.id)),[localEdges,nodes,focus]);
 const matching=useMemo(()=>partners.filter(p=>(p.node.id+' '+p.node.label).toLowerCase().includes(partnerQuery.toLowerCase().trim())),[partners,partnerQuery]);
 const suggestions=useMemo(()=>{const q=find.trim().toLowerCase();return q?graph.nodes.filter(n=>(n.id+' '+n.label).toLowerCase().includes(q)).sort((a,b)=>a.label.localeCompare(b.label)||a.id.localeCompare(b.id)).slice(0,12):[]},[graph,find]);
 const tableRows=useMemo(()=>all?filtered:filtered.filter(p=>p.candidate===focus||p.anchor===focus),[all,filtered,focus]);
 const groups=useMemo(()=>{const m=new Map<string,Pair[]>();for(const p of tableRows){const k=pairKey(p);m.set(k,[...(m.get(k)||[]),p])}return m},[tableRows]);
 const rows=unique?[...groups.values()].map(g=>g[0]):tableRows;
 const columns:ColumnDef<Pair>[]=[{accessorKey:'gene',header:'候选蛋白',cell:({row})=><button className="gene-link" onClick={()=>onProtein(row.original.candidate)}><span>{row.original.gene}<small className="cell-sub">{row.original.candidate}</small></span></button>},{accessorKey:'anchorGene',header:'调控锚点',cell:({row})=><button className="gene-link" onClick={()=>onProtein(row.original.anchor)}><span>{unique?[...new Set(groups.get(pairKey(row.original))!.map(p=>p.anchorGene))].join(' / '):row.original.anchorGene}<small className="cell-sub">{row.original.anchor}</small></span></button>},{accessorKey:'route',header:'筛选路径'},{accessorKey:'evidence',header:'证据来源',cell:({row})=><span className="evidence-tag">{row.original.route==='B3'?'异构体 PLM/PPLM':row.original.evidence}</span>},{accessorKey:'plm',header:'PLM-interact',cell:({getValue})=>display(getValue(),5)},{accessorKey:'pplm',header:'PPLM-PPI',cell:({getValue})=>display(getValue(),5)},{id:'sources',header:'配对详情',cell:({row})=><button className="text-link" onClick={()=>setEdge(groups.get(pairKey(row.original))!)}>{unique?groups.get(pairKey(row.original))!.length+'条来源':'原始行 '+row.original.row}</button>}];
 const center=nodes.get(focus);
 return <div className="interaction-explorer"><ReleaseFunnel release={release} route={route} onRoute={onRoute}/>
 <div className="filterbar"><div className="search-input"><Search size={17}/><Input aria-label="筛选互作记录" placeholder="在全部配对中检索基因或蛋白编号" value={query} onChange={e=>onQuery(e.target.value)}/></div><Select value={route} onValueChange={onRoute}><SelectTrigger className="filter-select" aria-label="筛选互作路径"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部筛选路径</SelectItem>{(['A','B1','B2','B3'] as Route[]).map(r=><SelectItem key={r} value={r}>{r} · {routeLabels[r]}</SelectItem>)}</SelectContent></Select><Select value={evidence} onValueChange={setEvidence}><SelectTrigger className="filter-select" aria-label="筛选互作证据"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部证据</SelectItem><SelectItem value="hi">含HI-union实验记录</SelectItem><SelectItem value="rf">含RF2预测支持</SelectItem><SelectItem value="iso">异构体PLM/PPLM</SelectItem></SelectContent></Select><Button variant="outline" aria-label="重置互作筛选" onClick={()=>{onQuery('');onRoute('all');setEvidence('all');setFocus('');setSelected('');setAll(false);setPlm('');setPplm('');setFind('')}}><RotateCcw size={16}/></Button></div>
 <div className="score-filters"><span>预测分数</span><label>PLM-interact ≥ <Input aria-label="最低PLM分数" type="number" min="0" max="1" step="0.01" value={plm} onChange={e=>setPlm(e.target.value)} placeholder="不限"/></label><label>PPLM-PPI ≥ <Input aria-label="最低PPLM分数" type="number" min="0" max="1" step="0.01" value={pplm} onChange={e=>setPplm(e.target.value)} placeholder="不限"/></label></div>
 <section className="panel network-studio ppi-studio"><div className="ppi-focus-panel"><div className="ppi-focus-top"><div><span className="eyebrow"><Focus size={15}/>蛋白中心探索</span><h2>{center?.label||'暂无匹配蛋白'}{center&&<code>{center.id}</code>}</h2></div><div className="graph-actions">{center&&<Button variant="outline" onClick={()=>onProtein(center.id)}>蛋白详情</Button>}<Button variant="outline" disabled={!history.some(id=>nodes.has(id))} onClick={previous}><ArrowLeft size={15}/>上一中心</Button><Button variant="outline" onClick={()=>{setAll(true);setSelected('');setFind('')}}><Orbit size={15}/>全网配对</Button></div></div>
 <div className="search-input"><Search size={17}/><Input value={find} aria-label="选择中心蛋白" placeholder="查找中心蛋白：基因名称或UniProt编号" onChange={e=>setFind(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&suggestions.length===1){e.preventDefault();activate(suggestions[0].id)}}}/></div>
 {find&&<div className="ppi-focus-results">{suggestions.map(n=><button key={n.id} onClick={()=>activate(n.id)}><strong>{n.label}</strong><code>{n.id}</code><span className={'node-role role-'+n.kind}>{roleName(n.kind)}</span></button>)}{!suggestions.length&&<p>当前筛选集合内没有匹配蛋白。</p>}</div>}
 </div>
 <div className="network-split"><div className="network-overview-pane"><PairOverview {...graph} focus={focus} onSelect={activate} onEdge={e=>setEdge(e.rows||[])}/></div><div className="network-center-pane">{center?<RadialRelations center={center} neighbors={partners.slice(0,limit).map(p=>p.node)} links={partners.slice(0,limit).map(p=>p.edge)} total={partners.length} selected={selected} onSelect={activate} onEdge={e=>setEdge(e.rows||[])} onMore={()=>setLimit(n=>n+40)}/>:<div className="graph-loading">当前筛选下没有中心关系</div>}</div></div>
 {center&&<section className="partner-panel"><div className="partner-heading"><h2>关联蛋白</h2><span>完整邻域 · {fmt(partners.length)} 个</span><div className="search-input"><Search size={15}/><Input aria-label="检索关联蛋白" placeholder="在关联蛋白中检索" value={partnerQuery} onChange={e=>setPartnerQuery(e.target.value)}/></div></div>
 <div className="partner-rows">{matching.slice(partnerPage*8,partnerPage*8+8).map(({node:n,edge:e})=><article key={n.id} className={selected===n.id?'selected':''}><button className="partner-identity" onClick={()=>activate(n.id)}><strong>{n.label}</strong><code>{n.id}</code><span className={'node-role role-'+n.kind}>{roleName(n.kind)}</span></button><button className="partner-evidence" onClick={()=>setEdge(e.rows||[])}>{[...new Set((e.rows||[]).map(p=>p.route==='B3'?'PLM-interact / PPLM-PPI':p.evidence))].join(' · ')}<small>查看配对证据 · {e.rows?.length} 条来源</small></button><div className="partner-actions"><button onClick={()=>choose(n.id)}>设为中心</button><button onClick={()=>onProtein(n.id)}>查看详情</button></div></article>)}{!matching.length&&<p className="empty-state">没有匹配的关联蛋白</p>}</div>
 <div className="pagination"><span>{fmt(matching.length)} 个 · 每页8个</span><div><Button size="icon-sm" variant="outline" aria-label="关联蛋白上一页" disabled={!partnerPage} onClick={()=>setPartnerPage(p=>p-1)}><ChevronLeft size={14}/></Button><span>{partnerPage+1}/{Math.max(1,Math.ceil(matching.length/8))}</span><Button size="icon-sm" variant="outline" aria-label="关联蛋白下一页" disabled={(partnerPage+1)*8>=matching.length} onClick={()=>setPartnerPage(p=>p+1)}><ChevronRight size={14}/></Button></div></div></section>}
 </section>
 {!graph.nodes.length&&<div className="empty-state">当前筛选没有互作记录；可重置条件后继续探索。</div>}
 <ReaderNote title="互作证据与浏览说明"><p>HI-union 提供实验记录；RF2-final80/90 为官方筛选集合，不是单条边的原始评分。基因映射支持与特定异构体预测保留各自证据分辨率。分数筛选仅作用于已提供的数值，不将缺失值填零。</p><p>节点颜色表示蛋白角色，连线颜色表示证据来源；多色连线保留多来源支持。PPI 不添加方向，空间位置和线色不表示分子距离、亲和力或统一互作强度。</p><p>初始中心为当前集合中连接数最多的候选蛋白，并列时按蛋白编号排序，仅作为浏览起点，不代表生物学优先级。中心图按基因名称、蛋白编号稳定排序，默认展示 40 个关联蛋白，可继续展开；关联列表和配对数据库始终保留完整邻域。</p></ReaderNote>
 <div className="ppi-database-heading"><h2>{all?'完整配对数据库':'当前中心的配对记录'}</h2><p>{all?'所有满足全局筛选条件的配对':(center?.label||'当前中心')+' 的完整配对'}</p></div>
 <div className="table-mode"><Tabs value={unique?'unique':'raw'} onValueChange={v=>setUnique(v==='unique')}><TabsList><TabsTrigger value="raw">来源记录 · {fmt(tableRows.length)}</TabsTrigger><TabsTrigger value="unique">唯一配对 · {fmt(groups.size)}</TabsTrigger></TabsList></Tabs><Button variant="outline" disabled={!rows.length} onClick={()=>exportTSV('互作配对_当前筛选.tsv',rows.map(p=>({...p,sourceRows:unique?groups.get(pairKey(p))!.map(x=>x.row).join(';'):p.row,aliases:unique?groups.get(pairKey(p))!.map(x=>x.anchorGene).join(';'):p.anchorGene})))}><Download size={15}/>导出视图</Button></div><DataTable data={rows} columns={columns} label="互作配对数据库"/><AtlasMethods page="pairs" docs={docs}/>
 <Sheet open={!!edge} onOpenChange={o=>{if(!o)setEdge(null)}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>配对证据</SheetTitle><SheetDescription>逐项保留来源及基因别名；未提供的分数不填零。</SheetDescription></SheetHeader><div className="detail-body">{edge?.map(p=><section key={p.id}><h3>{p.gene} ↔ {p.anchorGene}</h3><p>{p.candidate} ↔ {p.anchor}</p><p>{p.evidence}</p><dl><dt>来源</dt><dd>交付配对表 · 第{p.row}行</dd><dt>筛选路径</dt><dd>{p.route}</dd><dt>PLM-interact</dt><dd>{display(p.plm,8)}</dd><dt>PPLM-PPI</dt><dd>{display(p.pplm,8)}</dd><dt>RF2原始分数</dt><dd>未提供</dd><dt>证据分辨率</dt><dd>{p.route==='B3'?'特定异构体预测':'代表序列／基因映射支持'}</dd></dl></section>)}</div></SheetContent></Sheet></div>;
}
