"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {Box,Maximize,Plus,Minus} from 'lucide-react';
import {Button} from '@/components/ui/button';
import AtlasGraph,{AtlasNode,AtlasEdge,endpoint} from '@/components/atlas-graph';
import {graphTheme} from '@/lib/graph-theme';
import {fmt} from '@/lib/release';
export const roleName=(kind:string)=>({candidate:'候选蛋白',anchor:'调控锚点',both:'候选／锚点'}[kind]||'蛋白');
const colors=graphTheme.colors;
export function PairOverview({nodes,links,focus,onSelect,onEdge}:{nodes:AtlasNode[];links:AtlasEdge[];focus:string;onSelect:(id:string)=>void;onEdge:(e:AtlasEdge)=>void}){
 return <AtlasGraph nodes={nodes} links={links} selected={focus} onNode={onSelect} onEdge={onEdge} title="互作全景" height={430} embedded overview/>;
}
export function RadialRelations({center,neighbors,links,selected,onSelect,onEdge,total,onMore}:{center:AtlasNode;neighbors:AtlasNode[];links:AtlasEdge[];selected:string;onSelect:(id:string)=>void;onEdge:(e:AtlasEdge)=>void;total:number;onMore:()=>void}){
 const [zoom,setZoom]=useState(1),[width,setWidth]=useState(700);const box=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!box.current)return;const o=new ResizeObserver(es=>setWidth(Math.max(300,es[0].contentRect.width)));o.observe(box.current);return()=>o.disconnect()},[]);
 useEffect(()=>{setZoom(1);box.current?.scrollTo({left:0,top:0})},[center.id]);
 const h=Math.max(430,Math.ceil(neighbors.length/2)*20+50),cy=h/2,cx=width/2,radius=Math.max(65,Math.min(190,width/2-138));
 const points=neighbors.map((n,i)=>{const side=i%2?-1:1,k=Math.floor(i/2),count=Math.ceil((neighbors.length-(i%2))/2),y=24+(k+.5)*(h-48)/Math.max(1,count);return {...n,x:cx+side*(radius-15+15*Math.sin((k+1)/(count+1)*Math.PI)),y,side}});
 const edgeMap=new Map(links.map(e=>[endpoint(e.source)===center.id?endpoint(e.target):endpoint(e.source),e]));
 return <section className="panel radial-panel embedded-graph"><div className="atlas-graph-header"><div><h2>蛋白中心关系</h2><span>展示 {neighbors.length} / {fmt(total)} 个关联蛋白</span></div><div className="graph-actions"><Button size="icon-sm" variant="outline" aria-label="放大中心关系图" onClick={()=>setZoom(z=>Math.min(2,z+.25))}><Plus size={14}/></Button><Button size="icon-sm" variant="outline" aria-label="缩小中心关系图" onClick={()=>setZoom(z=>Math.max(.75,z-.25))}><Minus size={14}/></Button><Button size="icon-sm" variant="outline" aria-label="适应中心关系图" onClick={()=>{setZoom(1);box.current?.scrollTo({left:0,top:0})}}><Maximize size={15}/></Button></div></div>
 <div className="radial-scroll" ref={box}><svg viewBox={'0 0 '+width+' '+h} style={{width:(zoom*100)+'%',minWidth:zoom===1?undefined:560*zoom}} role="group" aria-label={center.label+' 的无向互作关系'}>
 <defs><radialGradient id="radial-halo"><stop offset="0" stopColor="#dcefed" stopOpacity=".9"/><stop offset="1" stopColor="#f4f8fc" stopOpacity="0"/></radialGradient></defs><rect width={width} height={h} fill="#f4f8fc"/><circle cx={cx} cy={cy} r={Math.min(210,width/2)} fill="url(#radial-halo)"/><circle cx={cx} cy={cy} r={radius} stroke="#81b4c4" strokeOpacity=".22" fill="none" strokeDasharray="2 7"/>
 {points.map(n=>{const e=edgeMap.get(n.id)!;const kinds=[...new Set((e.rows||[]).flatMap(p=>p.route==='B3'?['isoform']:[...(p.evidence.includes('HI-union')?['experimental']:[]),...(p.evidence.includes('RF2')?['predicted']:[])]))];return <g key={'edge'+n.id} className="radial-edge" role="button" tabIndex={0} aria-label={'查看 '+center.label+' 与 '+n.label+' 的配对证据'} onClick={()=>onEdge(e)} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();onEdge(e)}}}><path d={'M'+cx+' '+cy+' Q '+(cx+n.side*radius*.55)+' '+cy+' '+n.x+' '+n.y} fill="none" stroke="transparent" strokeWidth="12"/>{kinds.map((kind,i)=><path key={kind} d={'M'+cx+' '+(cy+i*2)+' Q '+(cx+n.side*radius*.55)+' '+(cy+i*2)+' '+n.x+' '+(n.y+i*2)} fill="none" stroke={kind==='isoform'?colors.isoform:kind==='experimental'?colors.experimental:colors.predicted} strokeOpacity={selected&&selected!==center.id&&selected!==n.id?.22:.7} strokeWidth={selected===n.id?2:1}/>)}</g>})}
 {points.map(n=><g key={n.id} className={'radial-node '+(selected===n.id?'selected':'')} role="button" tabIndex={0} aria-label={'查看蛋白 '+n.label+' '+n.id} onClick={()=>onSelect(n.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(n.id)}}}><title>{n.label+' · '+n.id+' · '+roleName(n.kind)}</title><rect x={n.side>0?n.x-10:5} y={n.y-12} width={n.side>0?width-5-n.x: n.x+5} height="24" rx="6" fill={selected===n.id?'#e1ebf7':'transparent'}/>{n.kind==='anchor'?<rect x={n.x-4.5} y={n.y-4.5} width="9" height="9" rx="2" fill={colors[n.kind]}/>:<circle cx={n.x} cy={n.y} r="5" fill={colors[n.kind]}/>}<text x={n.x+n.side*13} y={n.y+4} textAnchor={n.side>0?'start':'end'} fill="#31516b" fontSize="11.5">{n.label.length>(width<500?11:19)?n.label.slice(0,width<500?9:17)+'…':n.label}</text></g>)}
 <g role="button" tabIndex={0} aria-label={'查看中心蛋白 '+center.label} onClick={()=>onSelect(center.id)} onKeyDown={e=>{if(e.key==='Enter')onSelect(center.id)}}><circle cx={cx} cy={cy} r="39" fill="#ffffff" stroke={colors[center.kind]} strokeWidth="1.5"/><circle cx={cx} cy={cy} r="29" fill="#e3f1f0"/><text x={cx} y={cy-3} textAnchor="middle" fill="#234e5b" fontSize={Math.max(7,Math.min(13,100/center.label.length))} fontWeight="600">{center.label}</text><text x={cx} y={cy+14} textAnchor="middle" fill="#567a8e" fontSize="9">{center.id}</text></g>
 </svg></div><div className="radial-footer"><div><span><i style={{background:colors.experimental}}/>HI-union</span><span><i style={{background:colors.predicted}}/>RF2集合</span><span><i style={{background:colors.isoform}}/>PLM/PPLM</span></div>{neighbors.length<total&&<Button variant="outline" onClick={onMore}>再展示40个关联蛋白</Button>}</div></section>;
}
