"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {Plus,Minus,Maximize,MapPin,Search,ChevronLeft,ChevronRight,Grid2X2,Ellipsis,ArrowDownToLine} from 'lucide-react';
import {graphTheme} from '@/lib/graph-theme';
import {fmt} from '@/lib/release';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type Point={id:string;x:number;y:number;kind:string;label?:string};
type Bin={key:string;x:number;y:number;total:number;proteins:number;anchors:number;terms:number};
type Grid={cell:number;level:number;max:number;total:number;bins:Bin[];type:string};
const palette=graphTheme.density;
function densityColor(t:number){const v=Math.max(0,Math.min(1,t))*(palette.length-1),i=Math.min(palette.length-2,Math.floor(v)),f=v-i;const a=palette[i].match(/\w\w/g)!.map(x=>parseInt(x,16)),b=palette[i+1].match(/\w\w/g)!.map(x=>parseInt(x,16));return 'rgb('+a.map((x,j)=>Math.round(x+(b[j]-x)*f)).join(',')+')'}
export default function NetworkOverview({mode,focus,onSelect,labels}:{mode:string;focus:string;onSelect:(id:string)=>void;labels:Map<string,any>}){
 const canvas=useRef<HTMLCanvasElement>(null),worker=useRef<Worker|null>(null),serial=useRef(0),latest=useRef<Record<string,number>>({});
 const [data,setData]=useState<{nodes:Point[];nodeCount:number;edgeCount:number}|null>(null),[grid,setGrid]=useState<Grid|null>(null),[error,setError]=useState('');
 const [width,setWidth]=useState(900),[view,setView]=useState({zoom:1,x:500,y:300}),[type,setType]=useState('all'),[style,setStyle]=useState('density'),[hover,setHover]=useState<Bin|null>(null),[busy,setBusy]=useState(false);
 const [region,setRegion]=useState<{x:number;y:number;size:number}|null>(null),[search,setSearch]=useState(''),[page,setPage]=useState(0),[regionData,setRegionData]=useState<{available:number;total:number;rows:Point[]}|null>(null);
 const drag=useRef<{x:number;y:number;vx:number;vy:number;moved:boolean}|null>(null),regionRef=useRef<HTMLDivElement>(null);
 const height=430,scale=Math.min(width/1000,height/600)*view.zoom,level=Math.min(5,Math.floor(Math.log2(view.zoom)));
 const request=(action:string,args:Record<string,unknown>={})=>{const requestId=++serial.current;latest.current[action]=requestId;worker.current?.postMessage({action,mode,requestId,...args})};
 useEffect(()=>{const w=new Worker('/Protein_digger/density-worker.js',{type:'module'});worker.current=w;setData(null);setGrid(null);setRegion(null);setRegionData(null);setType('all');setView({zoom:1,x:500,y:300});setError('');
  w.onmessage=({data:m})=>{if(latest.current[m.action]!==m.requestId)return;if(m.error){setError(m.error);setBusy(false);return;}if(m.action==='init')setData(m.result);if(m.action==='grid'){setGrid(m.result);setBusy(false);}if(m.action==='region')setRegionData(m.result)};
  w.onerror=()=>{setError('网络展示索引载入失败，可继续使用下方数据库。');setBusy(false)};request('init');return()=>{w.terminate();worker.current=null};
 },[mode]);
 useEffect(()=>{if(!data)return;setBusy(true);setHover(null);request('grid',{level,type})},[data,level,type]);
 useEffect(()=>{setPage(0);setRegionData(null)},[region,search,type]);
 useEffect(()=>{if(region&&data){setRegionData(null);request('region',{bounds:region,type,search,page})}},[region,search,page,type,data]);
 useEffect(()=>{if(!canvas.current)return;const o=new ResizeObserver(es=>setWidth(Math.max(240,es[0].contentRect.width)));o.observe(canvas.current.parentElement!);return()=>o.disconnect()},[]);
 const byId=useMemo(()=>new Map(data?.nodes.map(p=>[p.id,p])||[]),[data]);
 const binMap=useMemo(()=>new Map(grid?.bins.map(b=>[b.key,b])||[]),[grid]);
 const screen=(x:number,y:number)=>({x:(x-view.x)*scale+width/2,y:(y-view.y)*scale+height/2});
 const world=(x:number,y:number)=>({x:(x-width/2)/scale+view.x,y:(y-height/2)/scale+view.y});
 useEffect(()=>{const c=canvas.current;if(!c)return;const dpr=devicePixelRatio||1;c.width=width*dpr;c.height=height*dpr;c.style.width=width+'px';c.style.height=height+'px';const ctx=c.getContext('2d')!;ctx.scale(dpr,dpr);ctx.fillStyle=graphTheme.background;ctx.fillRect(0,0,width,height);
  if(style==='density'&&grid){for(const b of grid.bins){const p=screen(b.x,b.y),size=grid.cell*scale;if(p.x+size<0||p.x>width||p.y+size<0||p.y>height)continue;ctx.fillStyle=densityColor(grid.max===1?1:Math.log(b.total)/Math.log(grid.max));ctx.fillRect(p.x,p.y,Math.max(1,size-.65),Math.max(1,size-.65));}if(hover){const p=screen(hover.x,hover.y);ctx.strokeStyle=graphTheme.selection;ctx.lineWidth=1.5;ctx.strokeRect(p.x,p.y,grid.cell*scale,grid.cell*scale)}}
  if(style==='nodes'&&data){for(const n of data.nodes){if(type!=='all'&&!(type==='protein'?n.kind!=='term':n.kind===type))continue;const p=screen(n.x,n.y);if(p.x<0||p.x>width||p.y<0||p.y>height)continue;ctx.fillStyle=graphTheme.colors[n.kind]||graphTheme.colors.protein;ctx.beginPath();ctx.arc(p.x,p.y,1.4,0,Math.PI*2);ctx.fill()}}
  if(region){const p=screen(region.x,region.y);ctx.strokeStyle='#ac874e';ctx.setLineDash([4,4]);ctx.strokeRect(p.x,p.y,region.size*scale,region.size*scale);ctx.setLineDash([])}
  const n=byId.get(focus);if(n){const p=screen(n.x,n.y);if(p.x>=0&&p.x<=width&&p.y>=0&&p.y<=height){ctx.strokeStyle=graphTheme.selection;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.stroke();const text=labels.get(focus)?.gene||focus;ctx.font='600 12px Arial';const tw=ctx.measureText(text).width,tx=Math.max(8,Math.min(width-tw-16,p.x+13)),ty=Math.max(18,Math.min(height-15,p.y));ctx.fillStyle='#fffffff0';ctx.fillRect(tx-5,ty-14,tw+10,23);ctx.fillStyle=graphTheme.ink;ctx.fillText(text,tx,ty+2)}}
 },[data,grid,width,view,hover,focus,labels,style,type,region]);
 const zoom=(factor:number,x=width/2,y=height/2)=>{const p=world(x,y),z=Math.max(1,Math.min(32,view.zoom*factor)),s=scale*z/view.zoom;setView({zoom:z,x:p.x-(x-width/2)/s,y:p.y-(y-height/2)/s});setHover(null)};
 useEffect(()=>{const el=canvas.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const r=el.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.002),e.clientX-r.left,e.clientY-r.top)};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel)},[view,width]);
 const hit=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!grid)return null;const r=e.currentTarget.getBoundingClientRect(),p=world(e.clientX-r.left,e.clientY-r.top);return binMap.get(Math.floor(p.x/grid.cell)+':'+Math.floor(p.y/grid.cell))||null};
 const reset=()=>{setView({zoom:1,x:500,y:300});setRegion(null);setHover(null)};
 const selectBin=(b:Bin)=>{if(!grid)return;setRegion({x:b.x,y:b.y,size:grid.cell});setSearch('');setPage(0);setView(v=>({zoom:Math.min(32,v.zoom*2),x:b.x+grid.cell/2,y:b.y+grid.cell/2}));};
 return <section className="panel network-global density-panel embedded-graph"><div className="atlas-graph-header"><div><h2>{mode==='annotation'?'功能注释全景':'调控网络全景'}</h2><span>{data?fmt(data.nodeCount)+' 个节点 · '+fmt(data.edgeCount)+' 条关系':'正在载入冻结布局…'}</span></div><div className="graph-actions"><Button variant="outline" size="icon-sm" aria-label="放大密度图" onClick={()=>zoom(1.6)}><Plus size={16}/></Button><Button variant="outline" size="icon-sm" aria-label="缩小密度图" onClick={()=>zoom(1/1.6)}><Minus size={16}/></Button><Button variant="outline" onClick={reset}><Maximize size={15}/>全景</Button><Button variant="outline" disabled={!byId.has(focus)} onClick={()=>{const n=byId.get(focus)!;setView({zoom:8,x:n.x,y:n.y})}}><MapPin size={15}/>定位当前蛋白</Button></div></div>
 <div className="density-toolbar"><div role="group" aria-label="节点类型">{[['all','全部节点'],['protein','蛋白（含锚点）'],['anchor','仅锚点'],...(mode==='annotation'?[['term','功能术语']]:[])].map(([v,l])=><button key={v} aria-pressed={type===v} onClick={()=>setType(v)}>{l}</button>)}</div><div role="group" aria-label="全景显示方式"><button aria-pressed={style==='density'} onClick={()=>setStyle('density')}><Grid2X2 size={14}/>密度热图</button><button aria-pressed={style==='nodes'} onClick={()=>setStyle('nodes')}><Ellipsis size={15}/>节点视图</button></div></div>
 <div className="network-global-canvas density-canvas"><canvas ref={canvas} tabIndex={0} aria-label="网络布局节点密度；方向键平移，加减键缩放，Home返回全景。区域节点可在下方列表检索。" onKeyDown={e=>{if(['+','=','-','Home','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();if(e.key==='+'||e.key==='=')zoom(1.6);else if(e.key==='-')zoom(1/1.6);else if(e.key==='Home')reset();else if(e.key.startsWith('Arrow'))setView(v=>({...v,x:v.x+(e.key==='ArrowLeft'?-40:e.key==='ArrowRight'?40:0)/scale,y:v.y+(e.key==='ArrowUp'?-40:e.key==='ArrowDown'?40:0)/scale}))}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y,moved:false}}} onPointerMove={e=>{const d=drag.current;if(d){const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>4)d.moved=true;setView(v=>({...v,x:d.vx-dx/scale,y:d.vy-dy/scale}))}else setHover(hit(e))}} onPointerUp={e=>{if(drag.current&&!drag.current.moved){const b=hit(e);if(b)selectBin(b)}drag.current=null;e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>{drag.current=null}} onPointerLeave={()=>setHover(null)}/>
 {(!data||error)&&<div className="density-status">{error||'正在建立展示索引，下方数据库可继续操作…'}</div>}
 <div className="density-inspector" aria-live="polite">{hover?<><b>网格内 {fmt(hover.total)} 个节点</b><span>蛋白 {hover.proteins}（其中锚点 {hover.anchors}） · 功能术语 {hover.terms}</span><small>点击查看区域节点并放大</small></>:<><b>网络布局节点密度</b><small>{busy?'正在细分网格…':'当前筛选 '+fmt(grid?.total||0)+' 个节点'}</small></>}</div></div>
 <div className="density-legend"><span>每格节点数 · 对数色阶</span><div><i style={{background:'linear-gradient(90deg,'+palette.join(',')+')'}}/><div><span>1</span><span>{grid?.max?Math.max(1,Math.round(Math.sqrt(grid.max))):'—'}</span><span>{fmt(grid?.max||0)}</span></div></div><small>网格层级 {level+1} · {view.zoom.toFixed(1)}×</small><Button variant="ghost" onClick={()=>{setRegion({x:0,y:0,size:1000});setSearch('');setPage(0);requestAnimationFrame(()=>regionRef.current?.scrollIntoView({block:'nearest',behavior:'auto'}))}}><ArrowDownToLine size={14}/>浏览全部节点</Button></div>
 
 {region&&<div className="density-region" ref={regionRef}><div className="density-region-head"><div><h3>区域节点</h3><p>{regionData?fmt(regionData.available)+' 个节点 · 检索匹配 '+fmt(regionData.total)+' 个':'正在查询区域…'}</p></div><div className="search-input"><Search size={15}/><Input aria-label="搜索区域节点" placeholder="基因、蛋白编号或功能术语" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button variant="ghost" onClick={()=>setRegion(null)}>收起</Button></div><div className="density-region-rows">{regionData?.rows.map(n=><div key={n.id}><span className={'node-role role-'+n.kind}>{n.kind==='term'?'功能术语':n.kind==='anchor'?'调控锚点':'蛋白'}</span><span><strong>{n.label}</strong><small>{n.id.replace(/^term:/,'')}</small></span>{n.kind!=='term'&&<Button variant="outline" onClick={()=>onSelect(n.id)}>设为中心</Button>}</div>)}{regionData&&!regionData.total&&<p>当前区域没有匹配节点。</p>}</div><div className="pagination"><span>每页12个节点</span><div><Button variant="outline" size="icon-sm" aria-label="区域节点上一页" disabled={!page} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></Button><span>{page+1} / {Math.max(1,Math.ceil((regionData?.total||0)/12))}</span><Button variant="outline" size="icon-sm" aria-label="区域节点下一页" disabled={!regionData||(page+1)*12>=regionData.total} onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></Button></div></div></div>}
 </section>;
}
