"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {ColumnDef} from '@tanstack/react-table';
import {Search,Download,RotateCcw,Database,Layers,Focus,Info} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import DataTable from '@/components/data-table';
import AtlasGraph,{AtlasNode,AtlasEdge,endpoint} from '@/components/atlas-graph';
import AtlasMethods from '@/components/atlas-methods';
import ReaderNote from '@/components/reader-note';
import StageFunnel from '@/components/stage-funnel';
import NetworkExplorer from '@/components/network-explorer';
import {RecordRow,useAtlas,display,regulatoryLabels,tierLabels,depthLabels} from '@/lib/atlas';
import {Doc,fmt,exportTSV} from '@/lib/release';
type Props={page:string;query:string;onQuery:(s:string)=>void;onProtein:(s:string)=>void;go:(p:string,q?:string)=>void;docs:Doc[]};
const tableKeys:Record<string,string>={reference:'reference',a:'annotation',b1:'prediction',b2:'network',b3:'isoforms'};
const match=(r:RecordRow,q:string)=>`${r.accession} ${r.parent||''} ${r.gene} ${r.name}`.toLowerCase().includes(q.trim().toLowerCase());
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(s:string)=>void;options:[string,string][]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="filter-select" aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{label}</SelectItem>{options.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select>}
function Stats({items,onSelect,selected}:{items:{id:string;label:string;value:number;color?:string}[];onSelect:(id:string)=>void;selected?:string}){return <div className="atlas-stats">{items.map((s,i)=><button key={s.id} onClick={()=>onSelect(selected===s.id?'all':s.id)} aria-pressed={selected===s.id} className={selected===s.id?'selected':''}><span><i style={{background:s.color||['#5474d8','#279c98','#b99945','#9c78b4'][i%4]}}/>{s.label}</span><strong>{fmt(s.value)}</strong><small>查看记录</small></button>)}</div>}
function Scatter({rows,onSelect}:{rows:RecordRow[];onSelect:(a:string)=>void}){const ref=useRef<HTMLCanvasElement>(null);const [hover,setHover]=useState<RecordRow|null>(null);const bounds=useRef({w:800,h:360});useEffect(()=>{const canvas=ref.current;if(!canvas)return;const draw=()=>{const w=canvas.parentElement!.clientWidth,h=360,dpr=devicePixelRatio||1;bounds.current={w,h};canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';const c=canvas.getContext('2d')!;c.scale(dpr,dpr);c.fillStyle='#f7faff';c.fillRect(0,0,w,h);const left=58,right=w-24,top=22,bottom=h-45;c.fillStyle='#e5f2ee';c.fillRect((left+right)/2,top,(right-left)/2,(bottom-top)/2);c.strokeStyle='#cbd9e8';c.lineWidth=1;for(let i=0;i<=4;i++){const x=left+(right-left)*i/4,y=bottom-(bottom-top)*i/4;c.beginPath();c.moveTo(left,y);c.lineTo(right,y);c.moveTo(x,top);c.lineTo(x,bottom);c.stroke();c.fillStyle='#57718f';c.font='12px Arial';c.fillText(String(i/4),x-8,bottom+20);c.fillText(String(i/4),22,y+4);}c.setLineDash([5,4]);c.strokeStyle='#69849c';c.beginPath();c.moveTo((left+right)/2,top);c.lineTo((left+right)/2,bottom);c.moveTo(left,(top+bottom)/2);c.lineTo(right,(top+bottom)/2);c.stroke();c.setLineDash([]);for(const r of rows){if(r.deeploc_nucleus_prob==null||r.nlsexplorer_nls_prob_max==null)continue;const x=left+r.deeploc_nucleus_prob*(right-left),y=bottom-r.nlsexplorer_nls_prob_max*(bottom-top);c.fillStyle=r.both_gt_0p5?'#208f88aa':'#547bd945';c.beginPath();c.arc(x,y,r.both_gt_0p5?2.5:1.8,0,2*Math.PI);c.fill();}c.fillStyle='#42607d';c.font='13px Arial';c.fillText('DeepLoc 核定位分数',(w/2)-60,h-6);c.save();c.translate(13,h/2+55);c.rotate(-Math.PI/2);c.fillText('NLSExplorer 分数',0,0);c.restore();};draw();const o=new ResizeObserver(draw);o.observe(canvas.parentElement!);return()=>o.disconnect()},[rows]);const nearest=(e:React.MouseEvent)=>{const rect=ref.current!.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,{w,h}=bounds.current;let best:RecordRow|null=null,d=144;for(const r of rows){if(r.deeploc_nucleus_prob==null||r.nlsexplorer_nls_prob_max==null)continue;const dx=58+r.deeploc_nucleus_prob*(w-82)-x,dy=h-45-r.nlsexplorer_nls_prob_max*(h-67)-y,z=dx*dx+dy*dy;if(z<d){best=r;d=z}}return best};return <div className="panel score-scatter"><div className="panel-heading"><div><h2>双模型核定位评分</h2><p>右上象限：两项分数均严格大于0.5 · {fmt(rows.length)} 条当前记录</p></div></div><canvas ref={ref} aria-label="DeepLoc与NLSExplorer评分散点图；同一记录可从下方表格键盘访问" onMouseMove={e=>setHover(nearest(e))} onMouseLeave={()=>setHover(null)} onClick={e=>{const n=nearest(e);if(n)onSelect(n.accession)}}/><div className="scatter-caption">{hover?`${hover.gene} · ${hover.accession}　DeepLoc ${display(hover.deeploc_nucleus_prob)}　NLSExplorer ${display(hover.nlsexplorer_nls_prob_max)}`:'悬停查看分数，点击查看蛋白。'}</div></div>}
function CellMap({onSelect}:{onSelect:(s:string)=>void}){return <section className="panel cell-map"><h2>核定位证据示意</h2><svg viewBox="0 0 360 220" role="img" aria-label="细胞区室示意，不表示实际转位路径"><ellipse cx="180" cy="110" rx="145" ry="90" fill="#edf3fc" stroke="#93accb" strokeWidth="2"/><ellipse cx="180" cy="110" rx="65" ry="55" fill="#e2f0ec" stroke="#3e9b8a" strokeWidth="2"/><text x="180" y="108" textAnchor="middle" fill="#276f67">细胞核</text><text x="180" y="130" textAnchor="middle" fill="#587e78" fontSize="12">双模型定位支持</text><text x="275" y="110" textAnchor="middle" fill="#587494">胞质</text></svg><Button variant="outline" onClick={()=>onSelect('positive')}>查看双模型支持集合</Button><ReaderNote title="示意说明"><p>此图仅解释细胞区室，不模拟某条蛋白的真实入核轨迹。评分不足不等同于确定的胞质定位。</p></ReaderNote></section>}
export default function StageAtlas({page,query,onQuery,onProtein,go,docs}:Props){const {data,error}=useAtlas<RecordRow[]>(tableKeys[page]);const [group,setGroup]=useState('all'),[secondary,setSecondary]=useState('all'),[focus,setFocus]=useState('');useEffect(()=>{setGroup('all');setSecondary('all');setFocus('')},[page]);useEffect(()=>{setFocus('')},[query]);
 const {data:manifest}=useAtlas<RecordRow>('manifest');
 const rows=useMemo(()=>{if(!data)return [];return data.filter(r=>{if(!match(r,query))return false;if(page==='reference')return (group==='all'||group==='anchors'&&r.anchor||group==='A'&&r.partition==='A'||group==='B'&&r.partition==='B'||group==='a-input'&&r.partition==='A'&&!r.excluded||group==='b-input'&&r.partition==='B'&&!r.excluded||group==='excluded-A'&&r.partition==='A'&&r.excluded||group==='excluded-B'&&r.partition==='B'&&r.excluded)&&(secondary==='all'||secondary==='excluded'&&r.excluded||secondary==='eligible'&&!r.excluded);
 if(page==='a')return (group==='all'||r.regulatory_evidence_status===group||group==='focused'&&(r.regulatory_evidence_status==='KNOWN_COMPLEX_ASSOCIATED'||r.regulatory_evidence_status==='NO_KNOWN_REGULATORY_EVIDENCE'&&['UNDER_CHARACTERIZED','MIXED_MOONLIGHTING'].includes(r.final_tier)))&&(secondary==='all'||r.final_tier===secondary);
 if(page==='b1')return (group==='all'||group==='positive'&&r.both_gt_0p5||group==='deeploc'&&r.deeploc_gt_0p5||group==='nls'&&r.nlsexplorer_gt_0p5||group==='other'&&!r.both_gt_0p5)&&(secondary==='all'||secondary==='clipped'&&r.deeploc_was_clipped_gt_4000||secondary==='delivery'&&r.delivery.includes('B1'));
 if(page==='b2')return (group==='all'||group==='eligible'&&!r.b1Excluded||group==='selected'&&r.selected||group==='excluded'&&r.b1Excluded)&&(secondary==='all'||secondary==='covered'&&r.omnipath_out_edge_count>0||secondary==='delivery'&&r.delivery.includes('B2'));
 return (group==='all'||group==='parent'&&r.parentEligible||group==='selected'&&r.selected||group==='delivery'&&r.delivery.includes('B3'))&&(secondary==='all'||secondary==='b1-excluded'&&r.b1Excluded||secondary==='anchor-excluded'&&r.anchorExcluded||secondary==='unscored'&&(r.deeploc==null||r.nlsexplorer==null));})},[data,page,query,group,secondary]);
 const base:ColumnDef<RecordRow>[]=[{accessorKey:'gene',header:'基因／蛋白',cell:({row})=><button className="gene-link" onClick={()=>onProtein(row.original.accession)}><span>{row.original.gene||'未标注基因'}<small className="cell-sub">{row.original.accession}</small></span></button>},{accessorKey:'name',header:'蛋白名称',cell:({getValue})=><span className="protein-name">{String(getValue()||'—')}</span>}];
 const metric=(key:string,title:string,labels?:Record<string,string>):ColumnDef<RecordRow>=>({accessorKey:key,header:title,cell:({getValue})=><span>{labels?.[String(getValue())]||display(getValue())}</span>});
 const cols:ColumnDef<RecordRow>[]=page==='reference'?[...base,metric('length','长度（aa）'),metric('partition','核注释分区',{A:'核定位注释适用',B:'无适用核定位注释'}),{accessorKey:'anchor',header:'锚点',cell:({row})=>row.original.anchor?'调控锚点':'—'},metric('anchorSources','锚点来源'),{accessorKey:'excluded',header:'排除状态',cell:({row})=>row.original.excluded?'按锚点规则排除':'非锚点输入'}]:page==='a'?[...base,metric('regulatory_evidence_status','调控证据',regulatoryLabels),metric('final_tier','功能分层',tierLabels),metric('function_pmid_count','功能 PMID'),metric('study_depth','研究深度',depthLabels)]:page==='b1'?[...base,metric('deeploc_nucleus_prob','DeepLoc'),metric('nlsexplorer_nls_prob_max','NLSExplorer'),{accessorKey:'both_gt_0p5',header:'联合条件',cell:({row})=><span className={row.original.both_gt_0p5?'status-pass':'muted'}>{row.original.both_gt_0p5?'满足':'未满足'}</span>},metric('nlsexplorer_n_windows','序列窗口数')]:page==='b2'?[...base,{id:'networkFocus',header:'网络定位',cell:({row})=><button className="text-link" onClick={()=>{setFocus(row.original.accession);document.getElementById('network-center')?.scrollIntoView({behavior:'auto',block:'start'})}}>定位到网络</button>},metric('network_rank','排名'),metric('network_score','综合分'),metric('p_graph_distance','注释图百分位'),metric('p_shared_seed_idf','共享种子百分位'),metric('p_omnipath_distance','有向距离百分位'),metric('p_omnipath_reach','可达数百分位'),{accessorKey:'selected',header:'筛选状态',cell:({row})=>row.original.b1Excluded?'B1已覆盖':row.original.selected?'前2%候选':'未入选'}]:[...base,metric('parent','代表序列'),metric('length','长度（aa）'),metric('deeploc','DeepLoc'),metric('nlsexplorer','NLSExplorer'),{accessorKey:'selected',header:'保守分支',cell:({row})=>row.original.selected?'入选':row.original.deeploc==null||row.original.nlsexplorer==null?'未评分／不完整':'未入选'}];
 if(!data)return <div className="panel loading">{error||'正在载入完整阶段记录…'}</div>;
 const count=(pred:(r:RecordRow)=>boolean)=>data.filter(pred).length;
 const tierBase=data.filter(r=>match(r,query)&&(group==='all'||r.regulatory_evidence_status===group||group==='focused'&&(r.regulatory_evidence_status==='KNOWN_COMPLEX_ASSOCIATED'||r.regulatory_evidence_status==='NO_KNOWN_REGULATORY_EVIDENCE'&&['UNDER_CHARACTERIZED','MIXED_MOONLIGHTING'].includes(r.final_tier))));const tierCount=(id:string)=>tierBase.filter(r=>r.final_tier===id).length;
 const stats=page==='reference'?[{id:'all',label:'审校代表序列',value:data.length},{id:'A',label:'核定位注释适用',value:count(r=>r.partition==='A')},{id:'B',label:'无适用核定位注释',value:count(r=>r.partition==='B')},{id:'anchors',label:'调控锚点',value:count(r=>r.anchor)}]:page==='a'?Object.entries(regulatoryLabels).map(([id,label])=>({id,label,value:count(r=>r.regulatory_evidence_status===id)})):page==='b1'?[{id:'all',label:'完整输入',value:data.length},{id:'deeploc',label:'DeepLoc > 0.5',value:count(r=>r.deeploc_gt_0p5)},{id:'nls',label:'NLSExplorer > 0.5',value:count(r=>r.nlsexplorer_gt_0p5)},{id:'positive',label:'双模型共同支持',value:count(r=>r.both_gt_0p5)}]:page==='b2'?[{id:'all',label:'网络特征记录',value:data.length},{id:'excluded',label:'B1已覆盖',value:count(r=>r.b1Excluded)},{id:'eligible',label:'正式排名背景',value:count(r=>!r.b1Excluded)},{id:'selected',label:'前2%候选',value:count(r=>r.selected)}]:[{id:'all',label:'真实可变异构体',value:data.length},{id:'parent',label:'保守分支母本范围',value:count(r=>r.parentEligible)},{id:'selected',label:'保守分支候选',value:count(r=>r.selected)},{id:'delivery',label:'本批入选异构体',value:count(r=>r.delivery.includes('B3'))}];
 return <>{['a','b1'].includes(page)&&<div className="nuclear-route-cards" aria-label="核定位两条筛选路径">{[{id:'a',route:'A',title:'核定位注释与功能分层',note:'已有适用于代表序列的核定位注释，进一步评价调控功能证据。',count:manifest?.counts.annotation},{id:'b1',route:'B1',title:'序列驱动的核定位预测',note:'缺少适用核注释，使用DeepLoc与NLSExplorer评价潜在核定位。',count:manifest?.counts.prediction}].map(r=><button key={r.id} className={page===r.id?'active':''} aria-pressed={page===r.id} onClick={()=>go(r.id)}><span className={'route-tag route-'+r.route}>路径 {r.route}</span><strong>{r.title}</strong><p>{r.note}</p><span>{r.count!=null?fmt(r.count):'—'} 条输入{page===r.id?' · 当前查看':''}</span></button>)}</div>}<StageFunnel page={page} data={data} group={group} secondary={secondary} onSelect={(g,s='all')=>{setGroup(g);setSecondary(s);onQuery('');setFocus('')}}/>

 {page==='a'&&<section className="panel classification-map"><h2>功能分层</h2><p>当前筛选范围的功能分布</p><div className="category-bars">{Object.entries(tierLabels).filter(([k])=>tierCount(k)>0).map(([id,label])=><button className={secondary===id?'selected':''} key={id} onClick={()=>setSecondary(secondary===id?'all':id)}><span>{label}</span><div><i style={{width:Math.max(1,tierCount(id)/Math.max(1,tierBase.length)*100)+'%'}}/></div><strong>{fmt(tierCount(id))}</strong></button>)}</div><ReaderNote title="分类解释"><p>功能分层保留原始标签。研究不足与潜在多功能均不代表已经验证表观调控作用。</p></ReaderNote></section>}
 {page==='b1'&&<div className="localization-layout"><Scatter rows={rows} onSelect={onProtein}/><CellMap onSelect={setGroup}/></div>}
 {page==='b2'&&<NetworkExplorer focus={focus||[...rows].sort((a,b)=>(a.network_rank??Infinity)-(b.network_rank??Infinity)||a.accession.localeCompare(b.accession))[0]?.accession||''} onFocus={setFocus} onProtein={onProtein} query={query} onQuery={q=>{setFocus('');onQuery(q)}}/>}
 {page==='b3'&&<><div className="notice"><Info size={17}/><span>保守分支：152条异构体、112个基因。沿用历史 B1 排除集合；未评分不视为阴性。</span></div><IsoformComparison rows={rows} focus={focus} onProtein={onProtein}/></>}
 <section className="atlas-database"><div className="database-heading"><Database size={20}/><h2>蛋白数据库</h2><span>{fmt(rows.length)} / {fmt(data.length)} 条</span></div><div className="filterbar"><div className="search-input"><Search size={17}/><Input aria-label="搜索阶段蛋白" placeholder="基因、蛋白编号或名称" value={query} onChange={e=>onQuery(e.target.value)}/></div><Filter label="全部类别" value={group} onChange={setGroup} options={[...stats.filter(s=>s.id!=='all').map(s=>[s.id,s.label] as [string,string]),...(page==='reference'?[['a-input','A路线输入'],['b-input','B1/B2共同输入'],['excluded-A','A分区锚点排除'],['excluded-B','B分区锚点排除']]:page==='a'?[['focused','聚焦候选集合']]:[]) as [string,string][]]}/>{page==='a'?<Filter label="全部功能分层" value={secondary} onChange={setSecondary} options={Object.entries(tierLabels)}/>:<Filter label="全部状态" value={secondary} onChange={setSecondary} options={page==='reference'?[['excluded','按锚点规则排除'],['eligible','非锚点输入']]:page==='b1'?[['clipped','DeepLoc长序列截取'],['delivery','本批入选']]:page==='b2'?[['covered','OmniPath出边已覆盖'],['delivery','本批入选']]:[['unscored','分数未提供／不完整'],['b1-excluded','历史B1已覆盖'],['anchor-excluded','锚点排除']]}/>}<Button variant="outline" aria-label="重置阶段筛选" onClick={()=>{setGroup('all');setSecondary('all');setFocus('');onQuery('')}}><RotateCcw size={15}/></Button><Button variant="outline" disabled={!rows.length} onClick={()=>exportTSV(`${page}_当前筛选.tsv`,rows)}><Download size={15}/>导出</Button></div><DataTable data={rows} columns={cols} label="完整阶段蛋白数据库"/></section><AtlasMethods page={page} docs={docs}/></>;
}
function IsoformComparison({rows,focus,onProtein}:{rows:RecordRow[];focus:string;onProtein:(s:string)=>void}){const chosen=rows.find(r=>r.accession===focus)||rows[0];const siblings=chosen?rows.filter(r=>r.parent===chosen.parent):[];const max=Math.max(chosen?.canonicalLength||1,...siblings.map(r=>r.length));return <section className="panel isoform-comparison"><div className="panel-heading"><div><h2>{chosen?.gene||'异构体'} · 序列与定位对照</h2><p>代表序列与可变异构体的长度对照</p></div></div>{chosen&&<div className="isoform-track-row"><button className="text-link" onClick={()=>onProtein(chosen.parent)}>{chosen.parent}<small>代表序列</small></button><div className="isoform-length-track"><i style={{width:chosen.canonicalLength/max*100+'%'}}/></div><span>{chosen.canonicalLength} aa</span></div>}{siblings.slice(0,12).map(r=><div className="isoform-track-row" key={r.accession}><button className="text-link" onClick={()=>onProtein(r.accession)}>{r.accession}<small>{r.selected?'保守分支候选':'未入选保守分支'}</small></button><div className="isoform-length-track"><i className={r.selected?'selected':''} style={{width:r.length/max*100+'%'}}/></div><span>{r.length} aa</span></div>)}{siblings.length>12&&<p>图中显示前12条；完整记录见下方数据库。</p>}</section>}
